services:
    auth.provider.instant:
        class: arseniyk\instant\auth\provider\instant
        arguments:
            - @dbal.conn
            - @config
            - @request
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: auth.provider }