services:
    auth.provider.instant:
        class: arseniyk\instant\auth\provider\instant
        arguments:
            - @dbal.conn
            - @passwords.manager
        tags:
            - { name: auth.provider }